default_language_version:
  python: python3.11

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: './.venv/Scripts/python.exe -m mypy app tests'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: pytest
        entry: './.venv/Scripts/python.exe -m pytest'
        language: system
        pass_filenames: false
        stages: [pre-commit]
